### ISSUE TITLE
Not working properly 

### ISSUE THREAD

**Issue by TheBlapse** [StarsRivers/Mathplus#24]
Hey when I write different symbol's expression its not working 
![image](https://user-images.githubusercontent.com/76247922/131092346-62cb5025-e094-4c83-899d-bf1fdb60a775.png)
and the expression which is doing this issue is 
![image](https://user-images.githubusercontent.com/76247922/131092427-1301ca21-f503-49f5-964b-a455bd347a5c.png)
but if I write it in code blocks form then it is working 
![image](https://user-images.githubusercontent.com/76247922/131092496-81a494d5-d9a5-4d34-9acc-2ea997cd0c95.png)
![image](https://user-images.githubusercontent.com/76247922/131092623-99f7af9c-4356-4940-855a-dbd10b2e3979.png)

Can you fix this or help me why is it doing this!

Thank you

**Comment by TheBlapse** [comment]
bump!

**Comment by StarsRivers** [comment]
浩瀚星河官方账号邮件7天内处理
